const getColumns = [
  {
    "id": 1,
    "title": "İd",
  },
  {
    "id": 1,
    "number": "1",
    "firstName": "John",
    "lastName": "Doe",
    "phone": "1234567890",
    "town": "Some Town",
    "city": "Some City",
    "country": "Some Country",
},
{
    "id": 2,
    "number": "2",
    "firstName": "Jane",
    "lastName": "Smith",
    "phone": "0987654321",
    "town": "Another Town",
    "city": "Another City",
    "country": "Another Country",
},
{
    "id": 3,
    "number": "3",
    "firstName": "Alice",
    "lastName": "Johnson",
    "phone": "9876543210",
    "town": "Some Other Town",
    "city": "Some Other City",
    "country": "Some Other Country",
},
{
    "id": 4,
    "number": "4",
    "firstName": "Alice",
    "lastName": "Williams",
    "phone": "0123456789",
    "town": "Yet Another Town",
    "city": "Yet Another City",
    "country": "Yet Another Country",
},
{
    "id": 5,
    "number": "5",
    "firstName": "Alice",
    "lastName": "Brown",
    "phone": "1111111111",
    "town": "Some Town",
    "city": "Some City",
    "country": "Some Country",
},
{
    "id": 6,
    "number": "6",
    "firstName": "Alice",
    "lastName": "Davis",
    "phone": "2222222222",
    "town": "Another Town",
    "city": "Another City",
    "country": "Another Country",
},
{
    "id": 7,
    "number": "7",
    "firstName": "Alice",
    "lastName": "Wilson",
    "phone": "3333333333",
    "town": "Some Other Town",
    "city": "Some Other City",
    "country": "Some Other Country",
},
{
    "id": 8,
    "number": "8",
    "firstName": "Alice",
    "lastName": "Taylor",
    "phone": "4444444444",
    "town": "Yet Another Town",
    "city": "Yet Another City",
    "country": "Yet Another Country",
},
{
    "id": 9,
    "number": "9",
    "firstName": "Alice",
    "lastName": "Taylor",
    "phone": "5555555555",
    "town": "Some Town",
    "city": "Some City",
    "country": "Some Country",
},
{
    "id": 10,
    "number": "10",
    "firstName": "Alice",
    "lastName": "Taylor",
    "phone": "6666666666",
    "town": "Another Town",
    "city": "Another City",
    "country": "Another Country",
},
];

export default getColumns;